### ISSUE TITLE
[22311927 안진영] 브러시, 도형, 텍스트 이용 시 오류 발견

### ISSUE THREAD

**Issue by dkwldu** [insung0-dklee/OSS_Paint_2024-1#246]
Change Brush Color 버튼을 눌러도 색상 표가 나오지 않아 브러시 색상을 바꿀 수 없음.
shape의 Triangle 버튼을 눌러도 삼각형이 제대로 그려지지 않음.
airbrush 버튼을 눌러도 에어(스프레이) 브러시가 제대로 작동하지 않음.
텍스트 박스에 텍스트 입력 후 화면에 우클릭을 해도 해당 위치에 텍스트가 추가되지 않음.

**Comment by insung0-dklee** [comment]
버그 식별 +2
