### ISSUE TITLE
[22311931 최규원] 브러쉬가 계속 이어지는 버그, 브러쉬 색 변경이 안되는 버그, 도트 브러쉬 크기가 안바뀌는 버그 발견.

### ISSUE THREAD

**Issue by Kyuwony** [insung0-dklee/OSS_Paint_2024-1#247]
일반 브러쉬가 끊기지 않고 한 획으로 계속 이어짐
Change brush color 버튼을 눌러도 색상이 변경되지 않고 오류가 뜸
brush size를 바꿔도 도트 브러쉬의 간격만 바뀌고 크기가 바뀌지 않음
Erase Last Stroke, Rewrite Last Stroke 기능이 작동하지 않음

**Comment by insung0-dklee** [comment]
버그 식별 +2
