### ISSUE TITLE
[22112093 이택민] shape를 선택하고 나서 brush로 변경이 안되는 오류,  SolidBrush 오류, Change Brush Color 오류

### ISSUE THREAD

**Issue by imTeakMin** [insung0-dklee/OSS_Paint_2024-1#278]
1. shape 버튼을 누르고 도형을 그리고 난 뒤 brush 버튼을 눌러도 변경이 안되는 오류가 일어납니다.
2. Solid Brush가 이전에 그었던 선의 끝 점과 새롭게 긋는 선의 시작 점이 연결이 되는 오류가 일어납니다.
3. Change Brush Color 버튼을 눌러도 색을 변경할 수 있는 창이 나타나지 않습니다.

**Comment by insung0-dklee** [comment]
버그식별 +1
밑에 두 버그는 다른 학생이 먼저 식별했습니다.
