### ISSUE TITLE
[22012117 이강현] rewrite last stroke 버그, open new window 버그, Erase last stroke 버그

### ISSUE THREAD

**Issue by singa03277** [insung0-dklee/OSS_Paint_2024-1#356]
1. rewrite와 Erase를 사용했을 때 그때 선을 사용했을 때의 색과 굵기가 아니고 현재 적용된 펜의 색과 굵기로 다시 써지고 지워지는 버그 식별
2. open new window를 하고 그 새 창을 닫게 되면 처음에 실행되었던 창은 선을 그리는 등 canvas에서 마우스를 클릭을 인식하지 못하는 버그 식별

**Comment by insung0-dklee** [comment]
버그 식별 +2
