### ISSUE TITLE
[22112113 현우정] erase last stroke, rewrite last stroke 사용 시 곡선에 대한 버그, use case diagram 사용 이후 그림 그려지지 않는 버그 식별

### ISSUE THREAD

**Issue by UDyon** [insung0-dklee/OSS_Paint_2024-1#375]
<h2>main.py 코드 실행 시 발생하는 버그 3가지 입니다.</h2>

<h4>버그 1 - 1204번째 라인</h4>
erase last stroke 할 때 brush size가 2 이상인 곡선을 지우면 선이 이상하게 지워집니다. (잔상이 남음)
<br><br>
<h4>버그 2 - 1211번째 라인</h4>
rewrite last stroke 할 때도 선이 원래처럼 깔끔하게 그려지지 않고 끊어집니다. brush size가 클 수록 이 현상이 더 잘 보입니다.
<br><br>
<h4>버그 3 - 457번째 라인</h4>
use case diagram을 그리고 나면 선이 안 그려집니다. brush size 수정해도 안 그려지고, 선 종류를 수정해야 다시 그려집니다.

**Comment by insung0-dklee** [comment]
버그 식별 +2
버그 식별 +2
버그 식별 +2
