### ISSUE TITLE
[22112113 현우정] rewrite last stoke 할 때 선 두께 버그, erase last stroke 할 때 현재 설정된 브러시 두께만큼만 지워지는 버그, 토그 다크모드 버그 식별

### ISSUE THREAD

**Issue by UDyon** [insung0-dklee/OSS_Paint_2024-1#382]
<h2>main.py 코드 실행 시 발생하는 버그 3가지 입니다.</h2>

<h4>버그 1 - 1211번째 라인</h4>
brush size를 다양하게 하여 그림을 그린 뒤 rewrite last stroke 하면 선 두께 여러가지로 그렸던 것들이 rewrite last stroke 할 당시의 brush size에 맞춰 선 두께 일정하게 다시 그려지는 버그가 있습니다. 
<br><br>
<h4>버그 2 - 1204번째 라인</h4>
버그 1번과 같은 현상으로 두꺼운 brush size로 선을 그린 뒤 brush size를 더 작게 하고 erase last stroke 하면 두꺼운 선이 가장자리 쪽 테두리만 남고 그 중앙은 하얗게 지워집니다. (네온 사인처럼)
<br><br>
<h4>버그 3 - 59번째 라인</h4>
토글 다크모드 클릭하면 다크 모드가 적용되나, 토글인데도 불구하고 버튼을 다시 클릭하면 라이트 모드로 돌아오지 않습니다.

**Comment by insung0-dklee** [comment]
버그 식별 +2
