### ISSUE TITLE
[22311931 최규원] 에어브러쉬의 count와 distance 값을 + - 버튼을 이용해 조절해도 10으로 표기되는 버그 식별

### ISSUE THREAD

**Issue by Kyuwony** [insung0-dklee/OSS_Paint_2024-1#389]
+와 - 버튼으로 airbrush의 count와 distance를 변경하여도 수치가 10으로 표기되는 버그 식별.

표기만 10으로 되고 선을 그었을 때는 개수와 거리가 정상적으로 변경된 상태로 그어짐.

**Comment by insung0-dklee** [comment]
버그 식별 +2
