### ISSUE TITLE
[22112021 조웅] Grid, Erase Last Stroke, Rewrite Last Stroke, 그림판 닫기 버그 식별

### ISSUE THREAD

**Issue by Wooong-E** [insung0-dklee/OSS_Paint_2024-1#433]
1. Tools - Toggle Grid 시 지우개로 그림을 지울 떄, Grid도 같이 지워지는 버그.

2. 그림을 그리고 화면을 확대 혹은 축소를 한 후 Erase Last Stroke 실행이 안되는 버그.

3. 그림을 그리고 Erase Last Stroke 후 화면을 확대 혹은 축소를 한 후 Rewrite Last Stroke 실행 시 변경된 화면에 그림이 출력되는 버그.

4. 그림판을 닫을 때, "저장하시겠습니까?" 창이 뜰 시 해당 창을 닫으면 그림이 유지되는 것이 아닌, 저장 없이 그림판이 꺼지는 버그.

**Comment by insung0-dklee** [comment]
버그식별+2
