### ISSUE TITLE
[22012117 이강현] 브러쉬 double line 버그, reset brush 버그

### ISSUE THREAD

**Issue by singa03277** [insung0-dklee/OSS_Paint_2024-1#438]
1. double line으로 브러쉬를 설정하고 그리면 마우스 기준 왼쪽의 선만 그려지는 버그 식별
2. Reset brush를 누르면 굵기와 펜 종류에 대한 ui가 초기화되지 않고 그대로 유지되는 버그 식별
3.

**Comment by insung0-dklee** [comment]
버그식별+2
