### ISSUE TITLE
[22112047 장세헌] 스크롤 후 선을 그릴때의 버그, 브러쉬 변경시 버그

### ISSUE THREAD

**Issue by jangseheon** [insung0-dklee/OSS_Paint_2024-1#503]
메모장을 스크롤 하고 브러쉬를 사용해 선을 그리려 할 때 solid브러쉬 모드를 제외한 다른 브러쉬 모드를 사용할 때 스크롤 된 위치에 선이 생성되지않고 그림판이 켜지는 첫화면의 위치에 선이 그려지는 버그

브러쉬모드를 변경할 때 solid 모드로 선을 그리고 dotted를 제외한 모드로 선을 그리고 다시 solid모드로 선을 그릴 때 solid 브러쉬의 다른부분의 끝부분과 바꾼 뒤 그리는 solid모드의 첫번째 부분이 연결되버는 버그

**Comment by insung0-dklee** [comment]
버그식별+1
