### ISSUE TITLE
[22112021 조웅] 그림판 새 창 열기 버그+ shape arrow 버그 식별

### ISSUE THREAD

**Issue by Wooong-E** [insung0-dklee/OSS_Paint_2024-1#524]
1. 프로그램 실행 후 File - Open New Window 실행 시 가장 최근에 Open된 그림판을 제외하고 그림판의 작동이 중지되는 버그 식별.

2. shape - arrow 실행 시 연속으로 화살표 그림을 그릴 시 가장 최근에 그려진 화살표를 제외하고 방향표시가 지워지는 버그 식별.

**Comment by insung0-dklee** [comment]
버그식별+1
