### ISSUE TITLE
[22020408 박관규] redo 기능 버그 식별

### ISSUE THREAD

**Issue by Izching** [insung0-dklee/OSS_Paint_2024-1#569]
undo 기능 사용 후 가장 최근 시점까지 redo 기능 사용후에 또 redo 를 사용 시 과거에 undo 되었던 그림이 다시 나타나는 버그 식별 

예시) 
그림1
그림2 
그림3
undo(그림 3 undo),
undo(그림 2 undo), 
그림 4 
그림 5 
undo(그림 5 undo), 
redo (그림 5 redo), 
redo (그림 2 redo), 
redo (그림 3 redo)

**Comment by insung0-dklee** [comment]
버그식별+1
