### ISSUE TITLE
[22012109 김민우] 화살표 기능 작동 이상

### ISSUE THREAD

**Issue by lavermeanyou** [insung0-dklee/OSS_Paint_2024-1#598]
![image](https://github.com/insung0-dklee/OSS_Paint_2024-1/assets/165126660/a67c65b8-ec4a-4143-9613-1b6613fcc1b9)

화살표가 써지다가 갑자기 직선으로 바뀜 간헐적으로 나타나서 발생원인은 모르겠음 특정한 조건에서 발생하는 것 같음

**Comment by insung0-dklee** [comment]
버그식별+1
